// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"file-sharing/ent/file"
	"file-sharing/ent/predicate"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// FileUpdate is the builder for updating File entities.
type FileUpdate struct {
	config
	hooks    []Hook
	mutation *FileMutation
}

// Where appends a list predicates to the FileUpdate builder.
func (_u *FileUpdate) Where(ps ...predicate.File) *FileUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetFileSize sets the "file_size" field.
func (_u *FileUpdate) SetFileSize(v int64) *FileUpdate {
	_u.mutation.ResetFileSize()
	_u.mutation.SetFileSize(v)
	return _u
}

// SetNillableFileSize sets the "file_size" field if the given value is not nil.
func (_u *FileUpdate) SetNillableFileSize(v *int64) *FileUpdate {
	if v != nil {
		_u.SetFileSize(*v)
	}
	return _u
}

// AddFileSize adds value to the "file_size" field.
func (_u *FileUpdate) AddFileSize(v int64) *FileUpdate {
	_u.mutation.AddFileSize(v)
	return _u
}

// SetFileName sets the "file_name" field.
func (_u *FileUpdate) SetFileName(v string) *FileUpdate {
	_u.mutation.SetFileName(v)
	return _u
}

// SetNillableFileName sets the "file_name" field if the given value is not nil.
func (_u *FileUpdate) SetNillableFileName(v *string) *FileUpdate {
	if v != nil {
		_u.SetFileName(*v)
	}
	return _u
}

// SetMime sets the "mime" field.
func (_u *FileUpdate) SetMime(v string) *FileUpdate {
	_u.mutation.SetMime(v)
	return _u
}

// SetNillableMime sets the "mime" field if the given value is not nil.
func (_u *FileUpdate) SetNillableMime(v *string) *FileUpdate {
	if v != nil {
		_u.SetMime(*v)
	}
	return _u
}

// SetPassword sets the "password" field.
func (_u *FileUpdate) SetPassword(v string) *FileUpdate {
	_u.mutation.SetPassword(v)
	return _u
}

// SetNillablePassword sets the "password" field if the given value is not nil.
func (_u *FileUpdate) SetNillablePassword(v *string) *FileUpdate {
	if v != nil {
		_u.SetPassword(*v)
	}
	return _u
}

// ClearPassword clears the value of the "password" field.
func (_u *FileUpdate) ClearPassword() *FileUpdate {
	_u.mutation.ClearPassword()
	return _u
}

// SetMaxDownloads sets the "max_downloads" field.
func (_u *FileUpdate) SetMaxDownloads(v int) *FileUpdate {
	_u.mutation.ResetMaxDownloads()
	_u.mutation.SetMaxDownloads(v)
	return _u
}

// SetNillableMaxDownloads sets the "max_downloads" field if the given value is not nil.
func (_u *FileUpdate) SetNillableMaxDownloads(v *int) *FileUpdate {
	if v != nil {
		_u.SetMaxDownloads(*v)
	}
	return _u
}

// AddMaxDownloads adds value to the "max_downloads" field.
func (_u *FileUpdate) AddMaxDownloads(v int) *FileUpdate {
	_u.mutation.AddMaxDownloads(v)
	return _u
}

// ClearMaxDownloads clears the value of the "max_downloads" field.
func (_u *FileUpdate) ClearMaxDownloads() *FileUpdate {
	_u.mutation.ClearMaxDownloads()
	return _u
}

// SetToken sets the "token" field.
func (_u *FileUpdate) SetToken(v string) *FileUpdate {
	_u.mutation.SetToken(v)
	return _u
}

// SetNillableToken sets the "token" field if the given value is not nil.
func (_u *FileUpdate) SetNillableToken(v *string) *FileUpdate {
	if v != nil {
		_u.SetToken(*v)
	}
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *FileUpdate) SetExpiresAt(v time.Time) *FileUpdate {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *FileUpdate) SetNillableExpiresAt(v *time.Time) *FileUpdate {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// SetDownloadCount sets the "download_count" field.
func (_u *FileUpdate) SetDownloadCount(v int) *FileUpdate {
	_u.mutation.ResetDownloadCount()
	_u.mutation.SetDownloadCount(v)
	return _u
}

// SetNillableDownloadCount sets the "download_count" field if the given value is not nil.
func (_u *FileUpdate) SetNillableDownloadCount(v *int) *FileUpdate {
	if v != nil {
		_u.SetDownloadCount(*v)
	}
	return _u
}

// AddDownloadCount adds value to the "download_count" field.
func (_u *FileUpdate) AddDownloadCount(v int) *FileUpdate {
	_u.mutation.AddDownloadCount(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *FileUpdate) SetUpdatedAt(v time.Time) *FileUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the FileMutation object of the builder.
func (_u *FileUpdate) Mutation() *FileMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *FileUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *FileUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *FileUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *FileUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *FileUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := file.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *FileUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(file.Table, file.Columns, sqlgraph.NewFieldSpec(file.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.FileSize(); ok {
		_spec.SetField(file.FieldFileSize, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedFileSize(); ok {
		_spec.AddField(file.FieldFileSize, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.FileName(); ok {
		_spec.SetField(file.FieldFileName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Mime(); ok {
		_spec.SetField(file.FieldMime, field.TypeString, value)
	}
	if value, ok := _u.mutation.Password(); ok {
		_spec.SetField(file.FieldPassword, field.TypeString, value)
	}
	if _u.mutation.PasswordCleared() {
		_spec.ClearField(file.FieldPassword, field.TypeString)
	}
	if value, ok := _u.mutation.MaxDownloads(); ok {
		_spec.SetField(file.FieldMaxDownloads, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMaxDownloads(); ok {
		_spec.AddField(file.FieldMaxDownloads, field.TypeInt, value)
	}
	if _u.mutation.MaxDownloadsCleared() {
		_spec.ClearField(file.FieldMaxDownloads, field.TypeInt)
	}
	if value, ok := _u.mutation.Token(); ok {
		_spec.SetField(file.FieldToken, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(file.FieldExpiresAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DownloadCount(); ok {
		_spec.SetField(file.FieldDownloadCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDownloadCount(); ok {
		_spec.AddField(file.FieldDownloadCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(file.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{file.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// FileUpdateOne is the builder for updating a single File entity.
type FileUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *FileMutation
}

// SetFileSize sets the "file_size" field.
func (_u *FileUpdateOne) SetFileSize(v int64) *FileUpdateOne {
	_u.mutation.ResetFileSize()
	_u.mutation.SetFileSize(v)
	return _u
}

// SetNillableFileSize sets the "file_size" field if the given value is not nil.
func (_u *FileUpdateOne) SetNillableFileSize(v *int64) *FileUpdateOne {
	if v != nil {
		_u.SetFileSize(*v)
	}
	return _u
}

// AddFileSize adds value to the "file_size" field.
func (_u *FileUpdateOne) AddFileSize(v int64) *FileUpdateOne {
	_u.mutation.AddFileSize(v)
	return _u
}

// SetFileName sets the "file_name" field.
func (_u *FileUpdateOne) SetFileName(v string) *FileUpdateOne {
	_u.mutation.SetFileName(v)
	return _u
}

// SetNillableFileName sets the "file_name" field if the given value is not nil.
func (_u *FileUpdateOne) SetNillableFileName(v *string) *FileUpdateOne {
	if v != nil {
		_u.SetFileName(*v)
	}
	return _u
}

// SetMime sets the "mime" field.
func (_u *FileUpdateOne) SetMime(v string) *FileUpdateOne {
	_u.mutation.SetMime(v)
	return _u
}

// SetNillableMime sets the "mime" field if the given value is not nil.
func (_u *FileUpdateOne) SetNillableMime(v *string) *FileUpdateOne {
	if v != nil {
		_u.SetMime(*v)
	}
	return _u
}

// SetPassword sets the "password" field.
func (_u *FileUpdateOne) SetPassword(v string) *FileUpdateOne {
	_u.mutation.SetPassword(v)
	return _u
}

// SetNillablePassword sets the "password" field if the given value is not nil.
func (_u *FileUpdateOne) SetNillablePassword(v *string) *FileUpdateOne {
	if v != nil {
		_u.SetPassword(*v)
	}
	return _u
}

// ClearPassword clears the value of the "password" field.
func (_u *FileUpdateOne) ClearPassword() *FileUpdateOne {
	_u.mutation.ClearPassword()
	return _u
}

// SetMaxDownloads sets the "max_downloads" field.
func (_u *FileUpdateOne) SetMaxDownloads(v int) *FileUpdateOne {
	_u.mutation.ResetMaxDownloads()
	_u.mutation.SetMaxDownloads(v)
	return _u
}

// SetNillableMaxDownloads sets the "max_downloads" field if the given value is not nil.
func (_u *FileUpdateOne) SetNillableMaxDownloads(v *int) *FileUpdateOne {
	if v != nil {
		_u.SetMaxDownloads(*v)
	}
	return _u
}

// AddMaxDownloads adds value to the "max_downloads" field.
func (_u *FileUpdateOne) AddMaxDownloads(v int) *FileUpdateOne {
	_u.mutation.AddMaxDownloads(v)
	return _u
}

// ClearMaxDownloads clears the value of the "max_downloads" field.
func (_u *FileUpdateOne) ClearMaxDownloads() *FileUpdateOne {
	_u.mutation.ClearMaxDownloads()
	return _u
}

// SetToken sets the "token" field.
func (_u *FileUpdateOne) SetToken(v string) *FileUpdateOne {
	_u.mutation.SetToken(v)
	return _u
}

// SetNillableToken sets the "token" field if the given value is not nil.
func (_u *FileUpdateOne) SetNillableToken(v *string) *FileUpdateOne {
	if v != nil {
		_u.SetToken(*v)
	}
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *FileUpdateOne) SetExpiresAt(v time.Time) *FileUpdateOne {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *FileUpdateOne) SetNillableExpiresAt(v *time.Time) *FileUpdateOne {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// SetDownloadCount sets the "download_count" field.
func (_u *FileUpdateOne) SetDownloadCount(v int) *FileUpdateOne {
	_u.mutation.ResetDownloadCount()
	_u.mutation.SetDownloadCount(v)
	return _u
}

// SetNillableDownloadCount sets the "download_count" field if the given value is not nil.
func (_u *FileUpdateOne) SetNillableDownloadCount(v *int) *FileUpdateOne {
	if v != nil {
		_u.SetDownloadCount(*v)
	}
	return _u
}

// AddDownloadCount adds value to the "download_count" field.
func (_u *FileUpdateOne) AddDownloadCount(v int) *FileUpdateOne {
	_u.mutation.AddDownloadCount(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *FileUpdateOne) SetUpdatedAt(v time.Time) *FileUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the FileMutation object of the builder.
func (_u *FileUpdateOne) Mutation() *FileMutation {
	return _u.mutation
}

// Where appends a list predicates to the FileUpdate builder.
func (_u *FileUpdateOne) Where(ps ...predicate.File) *FileUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *FileUpdateOne) Select(field string, fields ...string) *FileUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated File entity.
func (_u *FileUpdateOne) Save(ctx context.Context) (*File, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *FileUpdateOne) SaveX(ctx context.Context) *File {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *FileUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *FileUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *FileUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := file.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *FileUpdateOne) sqlSave(ctx context.Context) (_node *File, err error) {
	_spec := sqlgraph.NewUpdateSpec(file.Table, file.Columns, sqlgraph.NewFieldSpec(file.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "File.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, file.FieldID)
		for _, f := range fields {
			if !file.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != file.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.FileSize(); ok {
		_spec.SetField(file.FieldFileSize, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedFileSize(); ok {
		_spec.AddField(file.FieldFileSize, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.FileName(); ok {
		_spec.SetField(file.FieldFileName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Mime(); ok {
		_spec.SetField(file.FieldMime, field.TypeString, value)
	}
	if value, ok := _u.mutation.Password(); ok {
		_spec.SetField(file.FieldPassword, field.TypeString, value)
	}
	if _u.mutation.PasswordCleared() {
		_spec.ClearField(file.FieldPassword, field.TypeString)
	}
	if value, ok := _u.mutation.MaxDownloads(); ok {
		_spec.SetField(file.FieldMaxDownloads, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMaxDownloads(); ok {
		_spec.AddField(file.FieldMaxDownloads, field.TypeInt, value)
	}
	if _u.mutation.MaxDownloadsCleared() {
		_spec.ClearField(file.FieldMaxDownloads, field.TypeInt)
	}
	if value, ok := _u.mutation.Token(); ok {
		_spec.SetField(file.FieldToken, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(file.FieldExpiresAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DownloadCount(); ok {
		_spec.SetField(file.FieldDownloadCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDownloadCount(); ok {
		_spec.AddField(file.FieldDownloadCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(file.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &File{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{file.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
