// Code generated by ent, DO NOT EDIT.

package ent

import (
	"file-sharing/ent/file"
	"file-sharing/ent/schema"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	fileFields := schema.File{}.Fields()
	_ = fileFields
	// fileDescToken is the schema descriptor for token field.
	fileDescToken := fileFields[6].Descriptor()
	// file.DefaultToken holds the default value on creation for the token field.
	file.DefaultToken = fileDescToken.Default.(func() string)
	// fileDescExpiresAt is the schema descriptor for expires_at field.
	fileDescExpiresAt := fileFields[7].Descriptor()
	// file.DefaultExpiresAt holds the default value on creation for the expires_at field.
	file.DefaultExpiresAt = fileDescExpiresAt.Default.(func() time.Time)
	// fileDescDownloadCount is the schema descriptor for download_count field.
	fileDescDownloadCount := fileFields[8].Descriptor()
	// file.DefaultDownloadCount holds the default value on creation for the download_count field.
	file.DefaultDownloadCount = fileDescDownloadCount.Default.(int)
	// fileDescCreatedAt is the schema descriptor for created_at field.
	fileDescCreatedAt := fileFields[9].Descriptor()
	// file.DefaultCreatedAt holds the default value on creation for the created_at field.
	file.DefaultCreatedAt = fileDescCreatedAt.Default.(func() time.Time)
	// fileDescUpdatedAt is the schema descriptor for updated_at field.
	fileDescUpdatedAt := fileFields[10].Descriptor()
	// file.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	file.DefaultUpdatedAt = fileDescUpdatedAt.Default.(func() time.Time)
	// file.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	file.UpdateDefaultUpdatedAt = fileDescUpdatedAt.UpdateDefault.(func() time.Time)
	// fileDescID is the schema descriptor for id field.
	fileDescID := fileFields[5].Descriptor()
	// file.DefaultID holds the default value on creation for the id field.
	file.DefaultID = fileDescID.Default.(func() string)
}
